from .py.simple_text_image import NODE_CLASS_MAPPINGS as _STI_NODES, NODE_DISPLAY_NAME_MAPPINGS as _STI_NAMES
from .py.audio_fade_out import NODE_CLASS_MAPPINGS as _AFO_NODES, NODE_DISPLAY_NAME_MAPPINGS as _AFO_NAMES
from .py.float32_color_correct import NODE_CLASS_MAPPINGS as _FCC_NODES, NODE_DISPLAY_NAME_MAPPINGS as _FCC_NAMES

from .comfyui_layer_style import NODE_CLASS_MAPPINGS as _LS_NODES, NODE_DISPLAY_NAME_MAPPINGS as _LS_NAMES
from .comfyui_layerstyle_advance import NODE_CLASS_MAPPINGS as _LSA_NODES, NODE_DISPLAY_NAME_MAPPINGS as _LSA_NAMES

NODE_CLASS_MAPPINGS = {**_STI_NODES, **_AFO_NODES, **_FCC_NODES, **_LS_NODES, **_LSA_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_STI_NAMES, **_AFO_NAMES, **_FCC_NAMES, **_LS_NAMES, **_LSA_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
