from .py.simple_text_image import NODE_CLASS_MAPPINGS as _STI_NODES, NODE_DISPLAY_NAME_MAPPINGS as _STI_NAMES
from .py.audio_fade_out import NODE_CLASS_MAPPINGS as _AFO_NODES, NODE_DISPLAY_NAME_MAPPINGS as _AFO_NAMES

NODE_CLASS_MAPPINGS = {**_STI_NODES, **_AFO_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_STI_NAMES, **_AFO_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
